### ISSUE TITLE
Add Event Highlighting

### ISSUE THREAD

**Issue by cstoddart** [cstoddart/meeting-scheduler#1]
Events that include the logged in user should be easily identifiable. Such events could be highlighted in a different color.

**Comment by corey-whaley** [comment]
I like the highlight of meetings that include the user.

How about a different highlighting (perhaps in a lighter gray) for events to which a user RSVP'd "NO" or deleted from their calendar?

**Comment by cstoddart** [comment]
Oh wow I hadn't noticed that you still show up as an attendee after you have deleted the event from your calendar. Great catch @corey-whaley!

**Comment by cstoddart** [comment]
This issue was moved to dialexa/meeting-scheduler#1
