### ISSUE TITLE
Not all meetings are shown in scheduler

### ISSUE THREAD

**Issue by corey-whaley** [cstoddart/meeting-scheduler#12]
I have some meetings on my calendar that are scheduled in specific rooms, but they do not show up on the scheduler. They don't seem to have a common thread, like recurring vs. non-recurring, or from a particular organizer.

Examples:

- **Audi Subscription Standup, 11:00 AM - 11:30 AM, weekly on weekdays, The Labyrinth**
<img width="444" alt="screen shot 2018-06-27 at 12 46 09 pm" src="https://user-images.githubusercontent.com/38895612/41990488-271bbc08-7a08-11e8-9cf1-a0f51fb45779.png">

- **Corey 1-1, 2:30 PM - 3:00 PM, weekly on Thursday, The Fish Bowl**
<img width="444" alt="screen shot 2018-06-27 at 12 47 14 pm" src="https://user-images.githubusercontent.com/38895612/41990521-40e3ed36-7a08-11e8-8959-7e12d68b3a61.png">

**Comment by cstoddart** [comment]
Thank you for posting this! I need to look into this more to see if the problem is in my event filtering or in the event creation.

To make debugging easier, we can look at the "EVENTS" console message that contains the raw event data before filtering.

**Comment by corey-whaley** [comment]
Checked a couple weeks of meetings on my calendar, and everything with an actual room booked shows up. Thanks!

**Comment by cstoddart** [comment]
Thank you for checking on that!

**Comment by cstoddart** [comment]
This issue was moved to dialexa/meeting-scheduler#12
