### ISSUE TITLE
Click + drag to scroll schedule

### ISSUE THREAD

**Issue by RowdyHowell** [cstoddart/meeting-scheduler#13]
It would be nice to be able to click and drag to view the schedule instead of having to horizontally scroll.

**Comment by cstoddart** [comment]
Hmmm yeah that does sound nice. You should currently be able to hold shift while scrolling to scroll horizontally, but some drag action could come in handy.

**Comment by cstoddart** [comment]
This issue was moved to dialexa/meeting-scheduler#13
