### ISSUE TITLE
Highlight events that I am a part of

### ISSUE THREAD

**Issue by RowdyHowell** [cstoddart/meeting-scheduler#14]
It would be useful if there was an indicator (different color?) for my events or events that I am invited to.

**Comment by cstoddart** [comment]
Yes!! I am definitely adding this.

Tracking progress here: https://github.com/cstoddart/meeting-scheduler/issues/1

**Comment by cstoddart** [comment]
This issue was moved to dialexa/meeting-scheduler#14
