### ISSUE TITLE
Exiting Modals

### ISSUE THREAD

**Issue by corey-whaley** [cstoddart/meeting-scheduler#21]
Would be nice to exit modals by hitting `Esc` in addition to the `X`. This might be part of #4.

**Comment by cstoddart** [comment]
100% on this. Adding ASAP

**Comment by cstoddart** [comment]
This has been added! 2f34069a7d357cb320a6279a29bf31abf07e65e8

**Comment by cstoddart** [comment]
This issue was moved to dialexa/meeting-scheduler#21
